name: hello

on: 
  push: 
    branches: 
      - main
jobs: 
 log-hello:
   runs-on: ubuntu-latest
   steps: 
    - name: Checkout code
    - uses: actions/checkout@v2
    
    - name: Setup Nodejs
      uses: actions/setup-node@v2
      with: 
         node-version: '18.x'

    - name: install dependencies
    - run: npm install
    - name: Run index.js using Nodejs
    - run: node index.js
